name: Deploy Production

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
      - name: Install deps
        run: npm ci
      - name: Create .env file
        run: |
          echo "NEWT_SPACE_UID=${{ secrets.NEWT_SPACE_UID }}" >> .env
          echo "NEWT_CDN_API_TOKEN=${{ secrets.NEWT_CDN_API_TOKEN }}" >> .env
          echo "NEWT_API_TOKEN=${{ secrets.NEWT_API_TOKEN }}" >> .env
          echo "NEWT_APP_UID=${{ secrets.NEWT_APP_UID }}" >> .env
          echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> .env
          echo "TURNSTILE_SITE_KEY=${{ secrets.TURNSTILE_SITE_KEY }}" >> .env
          echo "TURNSTILE_SECRET_KEY=${{ secrets.TURNSTILE_SECRET_KEY }}" >> .env
      - name: Build
        run: npm run build
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=astro-cf-template
