name: Deploy Production

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.16.0
      - name: Install deps
        run: npm ci
      - name: Build
        run: npm run build
        env:
          NEWT_SPACE_UID: ${{ secrets.NEWT_SPACE_UID }}
          NEWT_CDN_API_TOKEN: ${{ secrets.NEWT_CDN_API_TOKEN }}
          NEWT_API_TOKEN: ${{ secrets.NEWT_API_TOKEN }}
          NEWT_APP_UID: ${{ secrets.NEWT_APP_UID }}
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=astro-cf-template
